kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.08956401716053501
    roll: -0
    pitch: 0
    yaw: 5.071730003849279e-05
  upper_arm:
    x: 7.570701266996488e-05
    y: 0
    z: 0
    roll: 1.570780999243756
    pitch: 0
    yaw: 1.222778882270485e-05
  forearm:
    x: -0.4252719934925572
    y: 0
    z: 0
    roll: 3.14140885869443
    pitch: -3.141486840023921
    yaw: -3.141551216785207
  wrist_1:
    x: -0.3920768556643368
    y: -0.0007839683223875579
    z: 0.1103173677297831
    roll: 0.00710636177763585
    pitch: 0.001122351253557539
    yaw: -0.0001027915626599502
  wrist_2:
    x: 8.085148232299397e-05
    y: -0.09477508287480087
    z: 0.0001032361733450685
    roll: 1.569707051751467
    pitch: 0
    yaw: -4.50630830353474e-05
  wrist_3:
    x: 3.58077690753481e-05
    y: 0.08249382179030061
    z: 0.0001208016366592702
    roll: 1.572260697673701
    pitch: 3.141592653589793
    yaw: 3.141555883342873
  hash: calib_8265285607221469861